name: Digger Workflow

on:
  workflow_dispatch:
    inputs:
      spec:
        description: Digger spec input
        required: true
      run_name:
        description: Digger run name
        required: false

run-name: '${{inputs.run_name}}'

jobs:
  digger-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # required to merge PRs
      actions: write       # required for plan persistence
      id-token: write      # required for workload-identity-federation
      pull-requests: write # required to post PR comments
      issues: read         # required to check if PR number is an issue or not
      statuses: write      # required to validate combined PR status

    steps:
      - uses: actions/checkout@v5
      #
      ###- uses: ./.github/workflows/infra_connect.yml
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v2

      - name: Load secrets
        id: load-secrets
        uses: 1password/load-secrets-action@v3
        with:
          export-env: false # Export loaded secrets as environment variables
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          #TF_ENCRYPT_PASSPHRASE: "op://perchnet/tf_encrypt_passphrase/password"
          #TF_API_TOKEN: "op://perchnet/terraform-token-github-actions/credential"
          TS_OAUTH_CLIENT_ID: "op://perchnet/tailscale-oauth-github-runner/username"
          TS_OAUTH_CLIENT_SECRET: "op://perchnet/tailscale-oauth-github-runner/credential"
          TFE_TOKEN: "op://perchnet/otaco/credential"
          TFE_HOSTNAME: "op://perchnet/otaco/hostname"
            
      #- uses: hashicorp/setup-terraform@v3
      #  with:
      #    cli_config_credentials_hostname: "${{ steps.load-secrets.outputs.TFE_HOSTNAME }}"
      #    cli_config_credentials_token: "${{ steps.load-secrets.outputs.TFE_TOKEN }}"

      - name: Inject API credentials into configuration
        run: op inject -i tf/secrets.op.tfvars -o tf/secrets.auto.tfvars
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ steps.load-secrets.outputs.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ steps.load-secrets.outputs.TS_OAUTH_CLIENT_SECRET }}
          tags: tag:github-runner
          ping: pve1.shark-perch.ts.net
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: v1.5.7
          cli_config_credentials_hostname: "${{ steps.load-secrets.outputs.TFE_HOSTNAME }}"
          cli_config_credentials_token: "${{ steps.load-secrets.outputs.TFE_TOKEN }}"

      ###
      - name: ${{ fromJSON(github.event.inputs.spec).job_id }}
        run: echo "job id ${{ fromJSON(github.event.inputs.spec).job_id }}"
      - uses: diggerhq/digger@vLatest
        with:
          setup-terraform: true
          digger-spec: ${{ inputs.spec }}
          digger-token: "${{ steps.load-secrets.outputs.TFE_TOKEN }}"
          configure-checkout: false
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
